---
title: "SDM"
author: "Kushan De Silva"
date: "May 1, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(deSolve)
START<-2015; FINISH<-2030; STEP<-0.25
simtime <- seq(START, FINISH, by=STEP)
head(simtime)
tail(simtime)

stocks <- c(sCustomers=10000)
auxs <- c(aGrowthFraction=0.08, aDeclineFraction=0.03)

model <- function(time, stocks, auxs){
with(as.list(c(stocks, auxs)),{
fRecruits<-sCustomers*aGrowthFraction
fLosses<-sCustomers*aDeclineFraction
dC_dt <- fRecruits - fLosses
return (list(c(dC_dt),
Recruits=fRecruits, Losses=fLosses,
GF=aGrowthFraction,DF=aDeclineFraction))
})
}

o<-data.frame(ode(y=stocks, times=simtime, func = model, parms=auxs, method="euler"))
head(o)
summary(o[,-c(1,5,6)])


library(ggplot2)
ggplot()+
geom_line(data=o,aes(time,o$sCustomers),colour="blue")+
geom_point(data=o,aes(time,o$sCustomers),colour="blue")+
ylab("Customers")+
xlab("Year")


library(gridExtra)

START <-0; FINISH <-100; STEP <-0.25
simtime <- seq(START, FINISH, by = STEP)
stocks <- c(sStock=100)
auxs <- c(aCapacity=10000,
          aRef.Availability=1,
          aRef.GrowthRate=0.10)

model <- function(time, stocks, auxs) {
  with(as.list(c(stocks, auxs)),{
    aAvailability <- 1-sStock/aCapacity
    aEffect <- aAvailability/aRef.Availability
    aGrowth.Rate <- aRef.GrowthRate*aEffect
    fNet.Flow <- sStock*aGrowth.Rate
    dS_dt <- fNet.Flow
    return(list(c(dS_dt),NetFlow=fNet.Flow,
                GrowthRate=aGrowth.Rate, Effect=aEffect,
                Availability=aAvailability))
  })
}


```

